language: generic
sudo: required
services:
    - docker

before-install:
    - docker build -t ksvijaynkl/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ksvijaynkl/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-164379663485"
    bucket_path: "docker-react"
    on:
        branch: master
